name: Build and deploy ASP.Net Core app to Azure Web App - backednrtest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build
        working-directory: ./auth-servce
        run: dotnet build --configuration Release

      - name: Publish
        working-directory: ./auth-servce
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./auth-servce/publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7796FDC35BEA4147A77F33479918FFCC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2852C7C5CD284E7C8C6B7F4B78F56DFE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_128A1D3B47A847D392A11E8340690FD6 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backednrtest'
          slot-name: 'Production'
          package: .